sudo: required
services: docker
language: python
jobs:
  include:
  - name: "Kubernetes 1.16"
    env: K8S_VERSION=1.16
  - name: "Kubernetes 1.15"
    env: K8S_VERSION=1.15
  - name: "Kubernetes 1.14"
    env: K8S_VERSION=1.14
  - name: "Kubernetes 1.13"
    env: K8S_VERSION=1.13
  - name: "Kubernetes 1.12"
    env: K8S_VERSION=1.12
  - name: "Kubernetes 1.11"
    env: K8S_VERSION=1.11
  - name: "Kubernetes 1.10"
    env: K8S_VERSION=1.10
  - name: "Kubernetes 1.9"
    env: K8S_VERSION=1.9
install:
  - pip3 install docker molecule openshift jmespath
script:
  - make test
