---
- import_playbook: ../default/prepare.yml

- name: Prepare operator resources
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
  tasks:
  - name: Create Custom Resource Definition
    k8s:
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/amazee.io_redisservices_crd.yaml'])) }}"

  - name: Ensure specified namespace is present
    k8s:
      api_version: v1
      kind: Namespace
      name: '{{ namespace }}'

  - name: Create RBAC resources
    k8s:
      definition: "{{ lookup('template', '/'.join([deploy_dir, item])) }}"
      namespace: '{{ namespace }}'
    with_items:
      - role.yaml
      - role_binding.yaml
      - service_account.yaml

  - name: Create lagoon-env ConfigMap
    k8s:
      state: present
      api_version: v1
      kind: ConfigMap
      namespace: "{{ namespace }}"
      name: lagoon-env
      definition:
        data:
          LAGOON_PROJECT: "{{ namespace }}"
