apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: redisservices.amazee.io
spec:
  group: amazee.io
  names:
    kind: RedisService
    listKind: RedisServiceList
    plural: redisservices
    singular: redisservice
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
