apiVersion: apps/v1
kind: Deployment
metadata:
  name: lagoon-raas
spec:
  replicas: 1
  selector:
    matchLabels:
      name: lagoon-raas
  template:
    metadata:
      labels:
        name: lagoon-raas
    spec:
      serviceAccountName: lagoon-raas
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: "8thom/lagoon-raas:v0.0.1"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: "8thom/lagoon-raas:v0.0.1"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "lagoon-raas"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: REDIS_HOST
              value: redis-host.local
            - name: REDIS_PORT
              value: "6379"
      volumes:
        - name: runner
          emptyDir: {}
